export enum CategoryGame {
    EUROGAMES = 'EUROGAMES',    
    AMERITRASH = 'AMERITRASH',
    PARTY = 'PARTY',        
    FILLER = 'FILLER',
    COOPERATIVE = 'COOPERATIVE',  
    DECK = 'DECK',
    LEGACY = 'LEGACY',       
    WARGAMES = 'WARGAMES',     
    BSTRACTO = 'ABSTRACTO',
    TEMATICO = 'TEMÁTICO',
    ROL = 'ROL',         
    LOSETA = 'LOSETA',
    TRABAJADOR = 'TRABAJADOR',       
    BORRADOR = 'BORRADOR',
    SOCIAL = 'SOCIAL',
    AREA = 'ÁREA',         
    ENGAÑO = 'ENGAÑO',
    ECONOMICO = 'ECONÓMICO',     
    DESTREZA = 'DESTREZA',
    NARRACION = 'NARRACIÓN', 
    EDUCATIVO = 'EDUCATIVO'
}