export enum CategoryGame {
    EUROGAMES = 'EUROGAMES',    
    AMERITRASH = 'AMERITRASH',
    PARTY = 'PARTY',        
    FILLER = 'FILLER',
    COOPERATIVE = 'COOPERATIVE',  
    DECK = 'DECK',
    LEGACY = 'LEGACY',       
    ABSTRACT = 'ABSTRACT',
    WARGAMES = 'WARGAMES',     
    THEMATIC = 'THEMATIC',
    ROLL = 'ROLL',         
    TILE = 'TILE',
    WORKER = 'WORKER',       
    DRAFTING = 'DRAFTING',
    ENGINE = 'ENGINE',       
    SOCIAL = 'SOCIAL',
    AREA = 'AREA',         
    BLUFFING = 'BLUFFING',
    ECONOMIC = 'ECONOMIC',     
    DEXTERITY = 'DEXTERITY',
    STORYTELLING = 'STORYTELLING', 
    EDUCATIONAL = 'EDUCATIONAL'
}